export interface OpenLibraryResponse {
    numFound: number
    start: number
    numFoundExact: boolean
    docs: Doc[]
    num_found: number
    q: string
    offset: any
}

interface Doc {
    key: string
    type: string
    seed: string[]
    title: string
    title_suggest: string
    title_sort: string
    edition_count: number
    edition_key: string[]
    publish_date?: string[]
    publish_year?: number[]
    first_publish_year?: number
    publish_place?: string[]
    last_modified_i: number
    ebook_count_i: number
    ebook_access: string
    has_fulltext: boolean
    public_scan_b: boolean
    publisher?: string[]
    language?: string[]
    author_key?: string[]
    author_name?: string[]
    publisher_facet?: string[]
    _version_: number
    author_facet?: string[]
    number_of_pages_median?: number
    oclc?: string[]
    lcc?: string[]
    readinglog_count?: number
    want_to_read_count?: number
    currently_reading_count?: number
    already_read_count?: number
    lcc_sort?: string
    isbn?: string[]
    cover_edition_key?: string
    cover_i?: number
    ia?: string[]
    ia_collection?: string[]
    ia_collection_s?: string
    lending_edition_s?: string
    lending_identifier_s?: string
    printdisabled_s?: string
    subject?: string[]
    ia_box_id?: string[]
    subject_facet?: string[]
    subject_key?: string[]
    contributor?: string[]
    ddc?: string[]
    ddc_sort?: string
    author_alternative_name?: string[]
    id_goodreads?: string[]
    id_librarything?: string[]
    lccn?: string[]
    place?: string[]
    place_key?: string[]
    place_facet?: string[]
    id_amazon?: string[]
    id_better_world_books?: string[]
    person?: string[]
    time?: string[]
    person_key?: string[]
    time_facet?: string[]
    person_facet?: string[]
    time_key?: string[]
    ratings_average?: number
    ratings_sortable?: number
    ratings_count?: number
    ratings_count_1?: number
    ratings_count_2?: number
    ratings_count_3?: number
    ratings_count_4?: number
    ratings_count_5?: number
    first_sentence?: string[]
}